packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'

catalog:
  # Core blockchain libraries
  viem: ^2.33.0
  '@uniswap/sdk-core': ^7.7.2
  '@uniswap/v3-sdk': ^3.25.2
  '@uniswap/v4-sdk': ^1.21.4
  '@privy-io/node': ^0.2.0

  # Testing
  vitest: ^3.1.4
  '@vitest/coverage-istanbul': ^3.1.4
  vite: ^6.3.2
  
  hono: ^4.7.10
  zod: 3.25.63
  '@neondatabase/serverless': ^1.0.0
  
  # Development tools
  eslint: ^9.24.0
  dotenv: ^16.5.0